[package]
name = "contract"
type = "contract"
authors = ["harsh bajpai"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory = "noir-projects/aztec-nr/aztec" }
token_contract = { path = "../deps/aztec-standards/src/token_contract" }
poseidon = { git = "https:/github.com/noir-lang/poseidon", tag = "v0.1.1" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory = "noir-projects/aztec-nr/address-note" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory = "noir-projects/aztec-nr/uint-note" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.3", directory = "noir-projects/aztec-nr/value-note" }
